# vim: tabstop=4:softtabstop=4:shiftwidth=4:noexpandtab

#get the project name from the project directory
THISPROJECT=`basename $(realpath .)`
THISDATE=`date +"%Y-%b-%d %R"`
REV_NUM=`git log --format=%cr | wc -l`
GITREV=`git log -1 --format=%h HEAD`

INIREAD=ini-read
INIWRITE=ini-write


#gcccpuopt-generated settings
MORE_CC_FLAGS=' '

all: init $(INIREAD) $(INIWRITE)
	@echo "\n* Compiled all targets for $(THISPROJECT) project, revision \033[1;33m$(GITREV)\033[m (#$(REV_NUM))."
	@exit 0
	
$(INIREAD): init src/ini-read.c
	@gcc -march=native -mfpmath=sse -msse3 -Ofast -O3 -o build/$(INIREAD) src/$(INIREAD).c src/utils.c src/minIni.o
	@strip build/$(INIREAD)
	@echo "* Build finished: '\033[0;37m$(INIREAD)\033[m'"
	@exit 0

$(INIWRITE): init src/ini-write.c
	@gcc -march=native -mfpmath=sse -msse3 -Ofast -O3 -o build/$(INIWRITE) src/utils.c src/minIni.o src/$(INIWRITE).c
	@strip build/$(INIWRITE)
	@echo "* Build finished: '\033[0;37m$(INIWRITE)\033[m'"
	@exit 0


init:
	@echo "//automatically generated by make" > src/build-date.h
	@echo " " >> src/build-date.h
	@echo "#define BUILD_DATE \"$(THISDATE)\"" >> src/build-date.h
	@exit 0

clean: 
	@if [ -f build/$(INIREAD) ]; then  rm "build/$(INIREAD)"; echo "* Removed $(INIREAD)"; fi
	@if [ -f build/$(INIWRITE) ]; then  rm "build/$(INIWRITE)"; echo "* Removed $(INIWRITE)"; fi
	@echo "\n* Cleaned all built files in build/."
	@exit 0



#.PHONY: test help

